"""add location to user_sessions

Revision ID: <auto-generated>
Revises: b85766486fe0
Create Date: 2026-07-19

"""
from alembic import op
import sqlalchemy as sa


revision = "add_location_user_sessions"  # you can keep the auto-generated revision id
down_revision = "b85766486fe0"


def upgrade():
    op.add_column("user_sessions", sa.Column("location", sa.String(), nullable=True))


def downgrade():
    op.drop_column("user_sessions", "location")